POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "brauliochavez2509@gmail.com",
    "password": "123456",
    "name": "braulio",
    "lastname": "chavez"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/v1/auth/verify-account?token=f0478dbf4c90cbd211f9f51d4b5529b16b3ef3d38377877baa528e4bc9170c19

###
POST http://localhost:3000/api/v1/auth/recover-password
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com"
}

###
POST http://localhost:3000/api/v1/auth/reset-password?token=b75061eae49aac7683f48b405a87a252d66afaf6cdbeb1856a434869c117ba8a
Content-Type: application/json

{
    "password": "654321"
}

### ---------------------------------REPORTS ---------------------------------
POST http://localhost:3000/api/v1/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyMjA2NDEsImV4cCI6MTc2NzMwNzA0MX0.kTMGmHDnQDrfdGYnvAqG2vjuuIrRSJOIWcqwfUpYPcg

{
    "title": "Reporte de problemas de basura",
    "description": "Reporte detallado de problemas visualizados en la zona.",
    "category": "OTHER",
    "latitude": 19.4326,
    "longitude": -99.1332
}

###
GET http://localhost:3000/api/v1/reports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyMjA4MDQsImV4cCI6MTc2NzMwNzIwNH0.8AB4NhXLa1hvecT4BAFQMC7KZpo5FLx1H4E_tX7t8j8

###
GET http://localhost:3000/api/v1/reports?category=OTHER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyMTMxNjEsImV4cCI6MTc2NzI5OTU2MX0.2h3UfWAbboZIsqwhJlvwbhcADw1Hjx8eV1AxvRXq0wc

###
GET http://localhost:3000/api/v1/reports/fe75c9d7-6dfa-46b9-a847-b194bd9cc1c8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyMjA4MDQsImV4cCI6MTc2NzMwNzIwNH0.8AB4NhXLa1hvecT4BAFQMC7KZpo5FLx1H4E_tX7t8j8

###
PATCH http://localhost:3000/api/v1/reports/0992f942-4022-439c-ad28-2114eae3e328
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyMTc3OTIsImV4cCI6MTc2NzMwNDE5Mn0.ppVmIaLjDNqlGmzm_X4KY85Bu6_TIlJyUgXDtsQ8EGk

{
    "title": "Reporte actualizado de problemas de basura",
    "description": "Descripción actualizada del reporte detallado de problemas visualizados en la zona.",
    "latitude": 19.4327,
    "longitude": -99.1333
}

###
PATCH http://localhost:3000/api/v1/reports/fe75c9d7-6dfa-46b9-a847-b194bd9cc1c8/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyMjA4MDQsImV4cCI6MTc2NzMwNzIwNH0.8AB4NhXLa1hvecT4BAFQMC7KZpo5FLx1H4E_tX7t8j8