POST http://localhost:3000/api/v1/auth/register
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com",
    "password": "123456",
    "name": "braulio",
    "lastname": "chavez"
}

###
POST http://localhost:3000/api/v1/auth/login
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com",
    "password": "123456"
}

###
POST http://localhost:3000/api/v1/auth/verify-account?token=f0478dbf4c90cbd211f9f51d4b5529b16b3ef3d38377877baa528e4bc9170c19

###
POST http://localhost:3000/api/v1/auth/recover-password
Content-Type: application/json

{
    "email": "brauliochaveza@gmail.com"
}

###
POST http://localhost:3000/api/v1/auth/reset-password?token=b75061eae49aac7683f48b405a87a252d66afaf6cdbeb1856a434869c117ba8a
Content-Type: application/json

{
    "password": "654321"
}

### ---------------------------------REPORTS ---------------------------------
POST http://localhost:3000/api/v1/reports
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

{
    "title": "Reporte de problemas de basura",
    "description": "Reporte detallado de problemas visualizados en la zona.",
    "category": "OTHER",
    "latitude": 19.4326,
    "longitude": -99.1332
}

###
GET http://localhost:3000/api/v1/reports
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/reports?status=COMPLETED
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjViMTRlZWU2LTdjMjYtNGVlZi1iZjNmLTlkMjIyYmQ3NDE2NiIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyOTk1NTAsImV4cCI6MTc2NzM4NTk1MH0.46RD065UD2gwkQjc_T6jqc_Ol-uMav4RDliMHZS4L1k

###
GET http://localhost:3000/api/v1/reports/fe75c9d7-6dfa-46b9-a847-b194bd9cc1c8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
PATCH http://localhost:3000/api/v1/reports/8bdfac63-fed9-417e-bc1f-fc16e126d71f
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NmRhMjZiLWUyZDQtNDE5ZS05ZjIzLTA3OTM3ZWI1NTM2MyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyNDAxMDMsImV4cCI6MTc2NzMyNjUwM30.F4Imt6z-7BgHgtI_PUX_bmmd5i8eSaKgLzs_rxwgSs4

{
    "title": "Reporte actualizado de problemas de basura",
    "description": "Descripción actualizada del reporte detallado de problemas visualizados en la zona.",
    "latitude": 19.4327,
    "longitude": -99.1333
}

###
PATCH http://localhost:3000/api/v1/reports/8bdfac63-fed9-417e-bc1f-fc16e126d71f/delete
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjE3NmRhMjZiLWUyZDQtNDE5ZS05ZjIzLTA3OTM3ZWI1NTM2MyIsInJvbGUiOiJVU0VSIiwiY2FuUmVwb3J0Ijp0cnVlLCJpYXQiOjE3NjcyNDAxMDMsImV4cCI6MTc2NzMyNjUwM30.F4Imt6z-7BgHgtI_PUX_bmmd5i8eSaKgLzs_rxwgSs4

###
PATCH  http://localhost:3000/api/v1/reports/92dda4e6-4cef-425c-a3d4-4c26f829cea6/status
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjQ4MDM4LCJleHAiOjE3NjczMzQ0Mzh9.pWMdJOGgZno2Em1COhOtHpjIerSmDHfWHlDndiZa8gw

{
    "status": "COMPLETED"
}

###
GET http://localhost:3000/api/v1/reports/c4169300-5d08-40c5-be45-f853d70c6667/history
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjQwMzA3LCJleHAiOjE3NjczMjY3MDd9.YBCNKrVifz_n1KESFKbY3guQP6CbjeoibJnn0KPwDWU 

###-----------------------------USERS-----------------------------------------
GET http://localhost:3000/api/v1/users?isActive=true&role=USER
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjQwMzA3LCJleHAiOjE3NjczMjY3MDd9.YBCNKrVifz_n1KESFKbY3guQP6CbjeoibJnn0KPwDWU

###
GET http://localhost:3000/api/v1/users/e1ec5b4c-f011-4aad-81f5-0347e9d745e8
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjQwMzA3LCJleHAiOjE3NjczMjY3MDd9.YBCNKrVifz_n1KESFKbY3guQP6CbjeoibJnn0KPwDWU

###
PATCH http://localhost:3000/api/v1/users/e1ec5b4c-f011-4aad-81f5-0347e9d745e8/ban
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjkxNDI5LCJleHAiOjE3NjczNzc4Mjl9.2icUV2qsFW4YphTpdnSItBeEijOljYOSU3anx1O-yis

{
    "banReason": "Violación de las normas de la comunidad."
}

###
PATCH http://localhost:3000/api/v1/users/e1ec5b4c-f011-4aad-81f5-0347e9d745e8/unban
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjkxNDI5LCJleHAiOjE3NjczNzc4Mjl9.2icUV2qsFW4YphTpdnSItBeEijOljYOSU3anx1O-yis

###
PATCH http://localhost:3000/api/v1/users/e1ec5b4c-f011-4aad-81f5-0347e9d745e8/toggle-report
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3MjkxNDI5LCJleHAiOjE3NjczNzc4Mjl9.2icUV2qsFW4YphTpdnSItBeEijOljYOSU3anx1O-yis

### 
PATCH http://localhost:3000/api/v1/users/e1ec5b4c-f011-4aad-81f5-0347e9d745e8/role
Content-Type: application/json  
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3Mjk0NjQ5LCJleHAiOjE3NjczODEwNDl9.5urqNkvxzSNmPANyP8rtfScZLeL8VW1OW_R5qyj5Swo

{
    "role": "ADMIN"
}

###------------------------------ANALYTICS---------------------------------
GET http://localhost:3000/api/v1/analytics/report-by-status?startDate=2025-06-01&endDate=2025-06-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT48

###
GET http://localhost:3000/api/v1/analytics/report-by-category?startDate=2025-06-01&endDate=2025-06-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/analytics/report-over-time?period=day&startDate=2025-06-01&endDate=2025-08-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/analytics/report-heat-map?startDate=2025-06-01&endDate=2025-06-07
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/analytics/average-resolution-time
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/analytics/time-per-status
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/analytics/status-transitions
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4

###
GET http://localhost:3000/api/v1/analytics/generate-report-pdf
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImM5ZDY1YzhmLWMxODEtNDYzYi05YTg1LTU1YWFiOTFkMzJmMyIsInJvbGUiOiJBRE1JTiIsImNhblJlcG9ydCI6dHJ1ZSwiaWF0IjoxNzY3NjM2OTEyLCJleHAiOjE3Njc3MjMzMTJ9.aQcIpoxeW3coAm7uRYEbKX9bLXHgw5vOHp1lW-IWZT4